version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-textbook-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: digitalbook2024
      POSTGRES_DB: digitalbook
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ai-textbook-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ai-textbook-backend-dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:digitalbook2024@postgres:5432/digitalbook
      REDIS_URL: redis://redis:6379
      JWT_SECRET: digitalbook-dev-secret-2024
      JWT_REFRESH_SECRET: digitalbook-dev-refresh-secret-2024
      SESSION_SECRET: digitalbook-dev-session-2024
      OPENAI_API_KEY: ${OPENAI_API_KEY:-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}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-textbook-frontend-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_dev_data:
  redis_dev_data: