version: '3.8'

services:
  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai-textbook-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://xn--220bu63c.com/api
    depends_on:
      - backend
      - postgres
      - redis
    networks:
      - ai-textbook-network
    restart: unless-stopped

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-textbook-backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:digitalbook2024@postgres:5432/digitalbook
      - REDIS_URL=redis://:digitalbook2024RedisPassword!@redis:6379
      - JWT_SECRET=${JWT_SECRET:-digitalbook-prod-secret-2024}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-digitalbook-prod-refresh-secret-2024}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-digitalbook-prod-session-2024}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-textbook-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ai-textbook-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=digitalbook2024
      - POSTGRES_DB=digitalbook
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./create_users.sql:/docker-entrypoint-initdb.d/create_users.sql
    networks:
      - ai-textbook-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache with Password
  redis:
    image: redis:7-alpine
    container_name: ai-textbook-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - ai-textbook-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "digitalbook2024RedisPassword!", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: ai-textbook-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - ai-textbook-network
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for SSL renewal
  certbot:
    image: certbot/certbot
    container_name: ai-textbook-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - ai-textbook-network

volumes:
  postgres_data:
  redis_data:

networks:
  ai-textbook-network:
    driver: bridge