version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:digitalbook2024@localhost:5432/digitalbook
      - NEXTAUTH_URL=http://xn--220bu63c.com
      - NEXTAUTH_SECRET=digitalbook-secret-2024
      - JWT_SECRET=digitalbook-jwt-secret-2024
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs