apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-textbook

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-keys-secret.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - nginx-deployment.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: ai-textbook-frontend
    newTag: latest
  - name: ai-textbook-backend
    newTag: latest

commonLabels:
  app.kubernetes.io/part-of: ai-textbook
  app.kubernetes.io/managed-by: kustomize